# Configuration des API Médicales (Secrets local)
# Ce fichier est ignoré par Git pour la sécurité.

# Gmail SMTP
mail.email=araartasnim7@gmail.com
mail.password=REMPLACER_PAR_CODE_APP_GMAIL

# Twilio WhatsApp
twilio.sid=AC_REMPLACER_PAR_TWILIO_SID
twilio.token=REMPLACER_PAR_TWILIO_TOKEN
twilio.number=+14155238886
